### ISSUE TITLE
Plugin Architecture

### ISSUE THREAD

**Issue by Ayman-Nageeb** [atk4/ui#1653] opened 2021-07-27 02:02 UTC
Hello, I need help

I am planning to build an extensible system (via plugins) using laravel

it for my project in the university ( I am a student )

the issue is that i don't know how to implement a plugins architecture in laravel

but you did it

i need to know how

so please give me any guide to start with

**Comment by mvorisek** [comment] 2021-07-27 09:30
duplicate of https://github.com/atk4/data/issues/885

**Closed as completed** 2021-07-27 09:30 UTC
