### ISSUE TITLE
Grid->addSelectable() don't have ability to select/unselect all

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#1749] opened 2022-03-04 18:42 UTC
![image](https://user-images.githubusercontent.com/1969119/156822698-1d7bf20b-c18c-4d77-93a2-e321d8ec077e.png)

We could nicely use header spot of selectable column to add checkbox (or dropdown) there to select / unselect all selectable checkboxes. I implemented something like that for very old toolkit version on which i had to work on. But that code will definitely not work with up to date toolkit.

**Comment by mvorisek** [comment] 2022-10-02 20:29
duplicate of https://github.com/atk4/ui/issues/1877

**Closed as completed by mvorisek** 2022-10-02 20:29 UTC
Labels: enhancement :+1:
