### ISSUE TITLE
Field with values (and descriptions) not properly shown in Crud

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1941] opened 2022-12-01 10:18 UTC
Steps to reproduce:
1. You have a model with a field containing 'values':
`$this->addField('unit_type_id', ['type' => 'integer', 'caption'  => 'Stock or capacity unit', 'values' => [1 => 'Stock unit', 2=> 'Capacity unit']]);`

2. You show a standard Crud which displays then all columns

Expected result:
The crud would show the column "unit_type_id" and shows the description ("Stock unit" or "Capacity unit" here) and not the value in the table.

Behaviour today:
The crud shows the values 1 or 2.

By the way, the Crud's "edit" form is correctly designed, showing the drop-down to select between "Stock unit" or "Capacity" unit.

**Comment by mvorisek** [comment] 2022-12-01 18:03
related with https://github.com/atk4/data/blob/4.0.0/src/Model/FieldPropertiesTrait.php#L32 setting, I am not sure if value is always wanted as key might be more compact, but I agree value might be wanted

**Comment by mkrecek234** [comment] 2022-12-01 20:48
@mvorisek I'd say for sure - this is how any form is configured, as the dropdown will never show the key, only the value for readability reasons.

**Comment by mvorisek** [comment] 2024-11-24 14:23
I belive this is duplicate of #676.

**Closed as completed by mvorisek** 2024-11-24 14:23 UTC
Labels: enhancement :+1:
