### ISSUE TITLE
Forms don't respect field caption

### ISSUE THREAD

**Issue by skondakov** [atk4/ui#106] opened 2017-04-06 06:35 UTC
When in the form's model there is a field with a 'caption', the caption is not  used for this field's label, but the default caption is used instead.

**Comment by DarkSide666** [comment] 2017-04-06 07:41
canyou give short testcase?

**Comment by romaninsh** [comment] 2017-04-06 08:47
Caused by https://github.com/atk4/data/issues/215

**Comment by acicovic** [comment] 2019-08-06 12:57
@skondakov according to Romans this is solved in #105 and #215 is closed as well. If you have time to confirm this, please do.

I will propose to close this issue but feel free to intervene if this is not fixed.

**Comment by DarkSide666** [comment] 2019-08-06 22:44
I would say - close it, but Romans wanted to close issues himself during weekly hangout so adding label.

**Closed** 2019-08-22 17:10 UTC
Labels: Compatibility, bug :beetle:, hangout agenda :speaker:
