### ISSUE TITLE
Column filter going on second row

### ISSUE THREAD

**Issue by morfeibox** [atk4/ui#554] opened 2018-09-03 11:28 UTC
If Grid column content is shorter than column name, filter icon go on the next row
<img width="61" alt="screen shot 2018-09-03 at 14 28 04 1" src="https://user-images.githubusercontent.com/24567371/44984492-99c2ed00-af85-11e8-80b1-43bcfd07cc8b.png">

**Comment by DarkSide666** [comment] 2018-09-03 17:07
Related 514

**Comment by ibelar** [comment] 2018-09-04 14:56
You can tweak the icon placement by changing the css class: atk-table-dropdown

By default it is meant to float right, which will cause icon to go on next row if not enough room. 

```
// table dropdown menu
.atk-table-dropdown {
  display: inline;
  float: right;
}
```

**Comment by morfeibox** [comment] 2018-09-05 13:00
Hi ibelar, I take a look and didn't find how and where I can add my custom css or even how can I change this css class?

**Comment by romaninsh** [comment] 2018-09-05 18:49
i think it should display properly by default. We don't have many CSS developers, i'll assign to @mayack, but he's busy working on other things.

**Comment by ibelar** [comment] 2018-09-05 19:45
In order to override the style, you would normally create your own css file and include the new css file in your app using App::requireCSS method.

```
$app->requireCSS('path/to/your/css/file');
```
Just redefine the rule for "atk-table.dropdown" in this new css file.

Hope this help.

**Comment by acicovic** [comment] 2019-07-28 15:19
Hi, a solution has been given to this problem and I don't know if it still occurs. #514 is already closed. I suggest we close this issue.

**Comment by DarkSide666** [comment] 2019-07-29 21:49
Not sure about closing this. Filter (or sorting) icons should *never* go on next line in my opinion.
That should be default and only one option how it should work.

**Comment by ibelar** [comment] 2019-10-26 16:30
This is a css issue. The css class name .atk-table-dropdown can be modify to fit everyone needs.
We should close this one.

**Comment by mvorisek** [comment] 2020-02-15 15:13
Not fixed, example from `demos/tablefilter.php`:
![image](https://user-images.githubusercontent.com/2228672/74590348-e4b3b180-500d-11ea-8add-d55ddeedc226.png)

Real estate is very expensive in comples UIs and for UX it is overall better to have (prererably always) the filter icons on the right side of the column headers.

**Comment by ibelar** [comment] 2020-02-15 16:48
Having it under the column name is the intended behavior now. 
If you need to have it on the same line, you can change/update the .atk-table-dropdown css class.
Using float right and changing top-margin value should give you what you need.

**Comment by DarkSide666** [comment] 2020-02-16 17:05
@ibelar Why can't we set this CSS as default to look nice out-of-the-box?

**Comment by ibelar** [comment] 2020-02-17 14:16
@DarkSide666 - The best compromise is to have the dropdown trigger icon on the next line, under the column label name by default. This way, it will always remain the same, independently of the column width. We cannot take into account that there will be enough space in each column to properly fit the sorting icon and the filtering icon on the same line.

If we set CSS to have all icons on the same line by default, then, when the column width is changed and becomes not wide enough, (see picture below) we will end up with the filter icon placed on the next line anyway. 

I believe that it is the developer responsibility to try placing it on the same line and live with the consequence. Only they will know what type of table they have to deal with. Plus, new CSS class introduced in PR #900 should give more freedom to adjust this to their needs.

see the same style set above with resize column.
<img width="853" alt="Screen Shot 2020-02-17 at 9 03 17 AM" src="https://user-images.githubusercontent.com/2204478/74660622-79302800-5164-11ea-87dd-e826c3653ade.png">

**Comment by georgehristov** [comment] 2020-02-17 14:38
How about placing the filter icon in front of the column label and opening the popup on click of the icon and the label text?

**Comment by mvorisek** [comment] 2020-02-17 14:53
@ibelar can this be solved with modern `flex` css property?

**Comment by ibelar** [comment] 2020-02-17 15:45
@mvorisek - I am not a CSS guru, so maybe.  

Guys, for me, this issue is closed. It might not be the prettiest solution but it is a workable one. There are workarounds to adapt to your needs, like changing CSS or using Table hook in order to generate your own column header.

**Closed** 2020-02-18 21:00 UTC
