### ISSUE TITLE
agiletoolkit.org is down

### ISSUE THREAD

**Issue by Jmos** [atk4/ui#1468] opened 2020-10-02 22:47 UTC
Whats the mater?

**Comment by DarkSide666** [comment] 2020-10-03 14:30
@romaninsh is working on that for some time already :)

**Comment by mvorisek** [comment] 2020-10-06 07:12
duplicate of https://github.com/atk4/ui/issues/1431

**Closed as completed by mvorisek** 2020-10-06 07:12 UTC

**Comment by Jmos** [comment] 2020-10-06 10:45
But still not working

**Comment by mvorisek** [comment] 2020-10-06 10:46
what is your usecase on that site?
