### ISSUE TITLE
Table->onRowClick() - Ignore click on checkboxes

### ISSUE THREAD

**Issue by acicovic** [atk4/ui#1601] opened 2021-02-01 13:23 UTC
`Table->onRowClick()` should not execute its action when a checkbox gets checked or unchecked.

**Comment by mvorisek** [comment] 2021-07-27 09:35
@acicovic please provide simple steps to replicate, if you know how to fix it, please submit a PR

**Comment by acicovic** [comment] 2021-08-05 19:18
No time for this unfortunately. I will ping @ibelar, I think it would be simple for him to see if this issue is still a thing.

This is the function I had made up to get the correct selector. This mainly excluded the checkbox column and action menu.

```php
    protected function generateRowClickSelector($class = 'handle-row-click')
    {
        $this->table->addClass("{$class} selectable");

        $excludeColumns = [];

        if (!empty($this->selection)) {
            $excludeColumns[] = ':first-child';
        }

        if (!empty($this->actionMenu)) {
            $excludeColumns[] = ':last-child';
        }

        $selector = "table.{$class} tr td";
        if (!empty($excludeColumns)) {
            $selector .= ":not('".implode(',', $excludeColumns)."')";
        }

        return $selector;
    }
```

And an example of how I used it:

```php
    /**
     * Executes model User Action when row is clicked.
     */
    protected function executeUserActionOnRowClick(string $action): void
    {
        $selector = $this->generateRowClickSelector();

        $this->on('click', $selector, $this->model->getUserAction($action), [
            $this->table->jsRow()->data('id'),
        ]);
    }
```

This was done on a class overriding `Grid`.

Hope that helps.

**Comment by mkrecek234** [comment] 2022-09-05 20:25
Fixed by #1655

**Comment by mvorisek** [comment] 2022-09-05 20:38
@mkrecek234 when some PR fixes some issue, the issue is closed by that PR when merged, no need to close it before...

**Comment by mkrecek234** [comment] 2022-09-06 02:42
This is a duplicate issue so no need to keep this topic open twice.

**Comment by mvorisek** [comment] 2022-09-06 03:47
where is the 2nd one?

the PR says it fixes this one...

**Comment by mkrecek234** [comment] 2022-09-06 04:05
You are right, I had erroneously memorised the PR discussion as an issue. Reopening until you contribute the test😉

**Closed as completed** 2022-09-07 18:58 UTC
Labels: bug :beetle:
