### ISSUE TITLE
Nested accordion section in form with required Fields

### ISSUE THREAD

**Issue by ibelar** [atk4/ui#605] opened 2018-11-27 18:30 UTC
Using a required field in a nested accordion section layout in form, i.e. an accordion section into another one, will not open proper accordion section if form is saved and will prevent nested accordion section to work properly after.

Step:

- create form using nested accordion section;
- add field in one nested section using required => true
- save form;

Nested accordion are not expandable anymore.

see demos file form-accordion-secton.php and add set required to field in nested section, say 'business_address'

**Comment by ibelar** [comment] 2018-11-27 18:33
Command need to be generate from top level accordion using the right section index in order to open the right section;
Furthermore, if top level accordion is closed, then top level accordion need to be open for nested section to open.

**Comment by mvorisek** [comment] 2022-10-03 22:04
duplicate of https://github.com/atk4/ui/issues/1728

**Closed** 2022-10-03 22:07 UTC
