### ISSUE TITLE
ScopeBuilder with errors on returned Scope

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#2186] opened 2024-03-20 16:51 UTC
- Go to Ui demo for Scopebuilder (https://ui.agiletoolkit.org/demos/form-control/scope-builder.php)
- Click Save.

Error: "Unexpected non-scalar value"

Expected result: ScopeBuilder should be able to store result in form's field, and typecastLoadField should be able to handle input.
 
My thinking would be to pass the result as json string into the field

**Comment by mvorisek** [comment] 2024-03-20 19:57
duplicate of #1843

I do not use ScopeBuilder, do you?

**Closed as completed** 2024-03-20 19:57 UTC

**Comment by mkrecek234** [comment] 2024-03-21 08:36
> duplicate of #1843
> 
> I do not use ScopeBuilder, do you?

It is very powerful and especially for administrators it might be a huge help. That would also justify to have it available even with the security concerns. Non-working it does not make sense at all.

**Comment by mvorisek** [comment] 2024-03-21 09:01
The ScopeBuilder component is piece of hacks, everytime I change something I need to fix ScopeBuilder too. It relies on vue instead of using native atk4 form control components.
