### ISSUE TITLE
"Select all" option on checkboxes in GRID

### ISSUE THREAD

**Issue by bedengler** [atk4/ui#2082] opened 2023-07-08 11:33 UTC
Feature request: if we add checkboxes through "addSelection();" to a GRID, there should be a checkbox in the first row. Clicking this checkbox selects ALL checkboxes of the GRID. 

That means also from other pages. So by clicking this checkbox, the checkboxes on ALL entries of the GRID are checked. 
If we have a GRID with 100 entries, 20 are shown per page and we select the "Select all" checkbox, all 100 entries are checked.

**Comment by mvorisek** [comment] 2023-07-08 11:53
duplicate of https://github.com/atk4/ui/issues/1877

**Closed as completed by mvorisek** 2023-07-08 11:53 UTC
