### ISSUE TITLE
Validation of form inside tabs

### ISSUE THREAD

**Issue by FabulousGee** [atk4/ui#402] opened 2018-03-09 09:05 UTC
This is an enhancement regarding forms divided into tabs (see https://forum.agiletoolkit.org/t/split-existing-form-into-tab/447/4 )

When adding a validation like
```
$f->onSubmit(function($f) use ($sc) {
				// In-form validation
				$errors=[];
				if (strlen($f->model['first_name']) < 3) {
					$errors[] = $f->error('first_name', 'too short, '.$f->model['first_name']);
				}
}
```
and the value of "first_name" is "A" onSubmit, then the validation kicks in and marks the corresponding field red. But if that field is hidden somewhere in another tab, I struggle searching it...

Maybe it would be possible to have the tab also in red color or anything?

**Comment by romaninsh** [comment] 2018-03-14 14:04
Thing is - there may be multiple errors across multiple tabs. Perhaps add labels showing number of errors per tab, but that is quite specific to your use case.

You can also catch the validation exception in your submission handler, review it, add some javascript output.

**Comment by romaninsh** [comment] 2018-03-14 14:04
I think this could be a good idea for an add-on - to implement a true multi-tab form, since I think there may be more tools needed. I'll add a label.

**Comment by mvorisek** [comment] 2022-10-03 21:53
duplicate of https://github.com/atk4/ui/issues/1728

**Closed by mvorisek** 2022-10-03 21:53 UTC
Labels: help wanted, add-on :electric_plug:
