### ISSUE TITLE
"confirm" no longer works for View::on('click', ...)

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1947] opened 2022-12-07 10:42 UTC
Steps to reproduce (Example):
- Make a crud, and add a menu item like this:
` $this->menu->addItem(['', 'icon' => 'trash red'])->on('click', null, ['confirm' => 'Do you really want to delete the selected positions? This action cannot be reverted.'])->atkAjaxec([
                'uri' => $jsCallbackDelete,
            ]);`

Throws now an error: 
`ErrorException: Undefined property: Atk4\Ui\JsFunction::$confirm`

This worked until recently - could not see any BC-break that describes what has changed, may be related to PR #1944

**Comment by mkrecek234** [comment] 2022-12-07 10:50
@mvorisek This continues to be needed, so the BC-break also renders these functions present in today's code erroneous:
https://github.com/atk4/ui/blob/fadc7680ed16ce15267968524bbc3217c8ea323b/src/Table/Column/ActionButtons.php#L70

https://github.com/atk4/ui/blob/18600ed8c82cbf7cd8f5700fc3c1e7aba1288582/src/Table/Column/ActionMenu.php#L87

https://github.com/atk4/ui/blob/9d32361b64e99bf516b87ec699312f71423819ff/src/UserAction/JsCallbackExecutor.php#L27

https://github.com/atk4/ui/blob/c535b9b45804394905e27506dae7c3df31f9f6d3/src/Table/Column/Delete.php#L36

**Comment by mvorisek** [comment] 2022-12-07 10:54
definitely, I will fix, thank you for the report

**Comment by mvorisek** [comment] 2022-12-07 15:04
@mkrecek234 check your codebase to never use `uri` - see https://github.com/atk4/ui/pull/1894

and open browser console and click thru your codebase/workflows to check if there are more problems

we are close to zero JS errors, later, they should throw visibly like php throws, so you will be always on the safe side

**Comment by mvorisek** [comment] 2022-12-07 15:20
issue introduced in #1942 at line:

https://github.com/atk4/ui/commit/775782c08ded42eadb3db3891e0c2e7d5357b3bc#diff-c5bb4a733c5ddd3bb0744ef4c29a8fd1e0bd5999fcf06b7f3cfef4c3d1926ce3R965

I would say it is not a bug, the problem is how an "optional argument is shifted" - any shifting is bad, thankfully almost all such "nice features" were already removed :)

The fix for your code is:

```diff
-$this->menu->addItem(['', 'icon' => 'trash red'])->on('click', null, ['confirm'...
+$this->menu->addItem(['', 'icon' => 'trash red'])->on('click', null, null, ['confirm'...
```

I already spent hours to make the handling and phpdoc as best as possible - the #1942 is more or less correct, as the 3rd and 4th param can be both of array type, so checking if "2nd argument was omit or not" is nearly impossible. The (unshifted) 3rd param should however be a list, so I will provide you a code to run once to detect places to change reliably.

**Comment by mkrecek234** [comment] 2022-12-07 21:55
@mvorisek Thank you that solves the issue - though I do not understand why this code still works:
https://github.com/atk4/ui/blob/18600ed8c82cbf7cd8f5700fc3c1e7aba1288582/demos/data-action/actions.php#L70

Shouldn't this then also be ..., null, null, ['confirm' => ...]? 
Also the links mentioned above?

**Comment by mvorisek** [comment] 2022-12-07 22:00
see the logic in https://github.com/atk4/ui/commit/775782c08ded42eadb3db3891e0c2e7d5357b3bc#diff-c5bb4a733c5ddd3bb0744ef4c29a8fd1e0bd5999fcf06b7f3cfef4c3d1926ce3R965

basically it is very hard to guess what you passed if the 3rd and 4th param can be both array

the example you posted above has probably not `null` `$executor` (vs. `null` in your original/issue example)

I have already spent hours in this topic when designing the last PRs, guessing is never good, nor easy to handle with phpstan, but I will try my best to detect this issue on runtime as `View::on()` is quite core method (and one of few where "optional/shifted arg" is still supported for BC reasons)

**Comment by mkrecek234** [comment] 2022-12-07 22:05
Sorry I misexplained: I do not get why the data-action/actions demo does not have the ['confirm',,,] then also as 4th parameter, but there then as third? Fully agree, guessing is bad. But why then is the actions demo still working? 

Also this code passes confirm as third argument:
https://github.com/atk4/ui/blob/9d32361b64e99bf516b87ec699312f71423819ff/src/UserAction/JsCallbackExecutor.php#L27

**Comment by mvorisek** [comment] 2022-12-07 22:10
> Fully agree, guessing is bad.

❤️

> But why then is the actions demo still working?

reread my comments, the guessing is based on the passed values, not the arg count purely

**Comment by mvorisek** [comment] 2022-12-11 22:23
closing, as explained, not a bug, code must throw otherwise the input interpretation is ambiguous as line:

https://github.com/atk4/ui/blob/9d32361b64e99bf516b87ec699312f71423819ff/src/View.php#L980

does another legacy guessing and we cannot know the user intentions otherwise ;-)

**Closed as completed by mvorisek** 2022-12-11 22:23 UTC
