### ISSUE TITLE
Tabs with wrong default active tab 

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1044] opened 2020-03-31 09:04 UTC
In the most recent version, the tab view chooses automatically the last tab as the default active tab. Prior behaviour was the first tab which makes more sense.

**Comment by ibelar** [comment] 2020-03-31 13:18
This is an issue with Fomantic-Ui starting with their release 2.7.8

see https://jsfiddle.net/ibelar/bjo1tnL9/

Suggest for now that you downgraded released for Fomantic-UI for version 2.7.4 in App::cdn property.

@romans - Should we downgraded Fomantic to version 2.7.4 in atk4/ui 2.1?

**Comment by DarkSide666** [comment] 2020-03-31 15:50
I think we should downgrade Fomantic while they don't fix this nasty bug.

**Comment by mvorisek** [comment] 2020-04-01 14:38
@ibelar I done a few tests and base on one Github example it seems that you need to call `.tab()` on selector that selects all tabs. Then the active tab is recognized withing that group and if not specified, the first one - as described in the issue desc - is choosed.

See https://jsfiddle.net/ur562o3z/ , https://jsfiddle.net/5x0n4vLc/

Does changing the selector help with this issue?

**Comment by ibelar** [comment] 2020-04-01 15:34
Understand that but it does not really apply to our use case in atk4/ui. Each individual tab need to be set up individually. The reason is that some tab needs to be load dynamically, via callback, while others don't. So they will use a different init option.

**Comment by mvorisek** [comment] 2020-04-03 07:40
Issue needs to be reevaluated once Fomatic UI is upgraded - related with PR #1058

**Comment by acicovic** [comment] 2020-04-26 15:44
Does anybody know if there's a link to the respective fomantic issue so we can track this more easily?

**Comment by romaninsh** [comment] 2020-05-05 00:09
I have just tested most up-to-date Fomantic release and the issue is still there. 2.8.4

I'll create a separate issue for this.

**Comment by lubber-de** [comment] 2020-05-29 17:44
I proposed a quick solution in Fomantic by adding a new option which, if disabled, will skip the autodetection of an active tab, so the old behavior will be used.
https://github.com/fomantic/Fomantic-UI/issues/1255#issuecomment-636092402

**Comment by lubber-de** [comment] 2020-05-29 18:33
Fixed in Fomantic UI by https://github.com/fomantic/Fomantic-UI/pull/1488
See your adjusted jsfiddle which now uses `autoTabActivation:false` https://jsfiddle.net/z632cfq5/1/

**Closed as completed** 2020-06-06 15:24 UTC
Labels: help wanted, good first issue :baby_bottle:, URGENT
