### ISSUE TITLE
Modal fails on js load if a php exception is thrown

### ISSUE THREAD

**Issue by pkly** [atk4/ui#651] opened 2019-02-15 10:23 UTC
If an exception is thrown in the `set()` function for a modal, the modal will fail to render completely and an error will appear in the console, the modal will stay unresponsive.

Test case
```php

$modal = $app->add(['Modal']);

$modal->set(function($m) use ($modal) {
    throw new \Exception("TEST!");
});

$button = $this->_app->add(['Button', 'Test modal']);
$button->on('click', $modal->show());
```

The following message will appear in the console:
Uncaught TypeError: Cannot create property 'id' on string '{"success":false,"message":"\n<div class [...]
pointing to the following code in the file /js/src/services/ModalService.js (67 line)
```js
onComplete: function(response, content) {
    const result = content.html(response.html);
    if (!result.length) {
        response.success = false;
        response.isServiceError = true;
        response.message = 'Modal service error: Unable to replace atk-dialog content in modal from server response. Empty Content.';
    } else {
        if ($modal.modal.settings.autofocus) {
            modalService.doAutoFocus($modal);
        }
        $modal.modal('refresh');
        //content is replace no need to do it in api
        response.id = null; // error here apparently
    }
}
```

It appears that this function does not actually try to read the response as JSON, instead opting to only read it as html.
Even though there's already handlers for this kind of behaviour, so maybe it's an oversight?
I've tried it with both a normal exception and \atk4\ui\Exception.

Using ATK4 UI 1.6.2 (slightly modified, although it's not related) / ATK4 Core 1.3.8

**Comment by PhilippGrashoff** [comment] 2019-02-15 13:33
IIRC there already is an open issue for this. Its not limited to Exceptions, any output like echo or var_dump also causes the modals to load forever.

**Comment by abbadon1334** [comment] 2019-02-19 07:09
but why? 

@pkly i try on mine and i don't get that error i get a modal error with the exception in it, bu ti see that button is add to _app, possible that $app and $this->_app are not in sync 

@PhilippGrashoff is not an issue is the normal behaviour, i think browser can't handle mixed format response, in place of output echo or var_dump directly to browser, enable debug and add monolog to log in app, open a terminal and tail -f while you are working.

from my point of view, atk4 is a jewel but you have to take care of don't break some stuff while testing

i use [Kint](https://github.com/kint-php/kint) but due to matrioska structure of atk4 u have to define like this : 

`\Kint\Kint::$max_depth = 1; // max 2`

if not it enter in recurring relations and loooooop

to log directly you can do this with `@` modifiers in from of it : 
`$this->app->debug(@d($var_to_dump));`

**Comment by pkly** [comment] 2019-02-19 07:52
My `$this->_app` is just an `\atk\ui\App` object, there's nothing wrong with it, it's the same one.

The issue is that the JS code for the modal does not expect an error, instead expecting a html response, which causes this error.

From what I've used of atk so far, it's neat, it's made a lot of things way simpler, but it has a lot of it's own issues, mostly related to modals and js reloads of items.

**Comment by abbadon1334** [comment] 2019-02-19 08:20
i don't get that error with develop version, but i have a modified version of App class, where i override the default cauchtException with this one : 

note : there is a part at the end ( if debug is enabled ) that save me some time on debugging trivial issues php<->js<->html<->browser 

```php
    /**
     * override Catch exception.
     *
     * @param mixed $exception
     */
    public function caughtException($exception)
    {
        $this->catch_runaway_callbacks = false;
        
        $AppClassName = get_class($this); // get extended app class
        $l            = new $AppClassName(false);
        $l->initLayout('Centered');
        
        //check for error type.
        if ($exception instanceof \atk4\dsql\Exception) {
            $l->layout->template->setHTML('Content', $exception->getHTML());
            $params = $exception->getParams();
            if (array_key_exists('query', $params)) {
                $l->layout->template->appendHTML('Content', nl2br($params['query']));
            }
        } elseif ($exception instanceof \atk4\core\Exception) {
            $l->layout->template->setHTML('Content', $exception->getHTML());
        } elseif ($exception instanceof \Error) {
            $l->layout->add(['Message',
                             get_class($exception) . ': ' . $exception->getMessage() . ' (in ' . $exception->getFile()
                             . ':' . $exception->getLine() . ')', 'error',
                            ]);
            $l->layout->add(['Text', nl2br($exception->getTraceAsString())]);
        } else {
            $l->layout->add(['Message', get_class($exception) . ': ' . $exception->getMessage(), 'error']);
        }
        
        if($this->debug !== false) // if debug is enabled log a more detailed exception
        {
            $debugMsg = [
                'EXCEPTION : ' . get_class($exception),
                ' ====================================== ',
                'MSG:' . $exception->getMessage(),
                'FILE:' . $exception->getFile(),
                'LINE:' . $exception->getLine(),
            ];
            
            if(is_callable([$exception,'getParams'])) {
                $params = $exception->getParams();
                if (count($params) > 0) {
        
                    $debugMsg[] = 'EXCEPTION PARAMS';
        
                    foreach ($params as $name => $value) {
            
                        if (is_object($value) || is_array($value)) {
                            if ($value instanceof View) {
                                $value = get_class($value);
                            } elseif (is_array($value)) {
                                $value = print_r($value, true);
                            } else {
                                $value = get_class($value);
                            }
                        }
            
                        $debugMsg[] = $name . ':' . $value;
                    }
                }
            }
            
            $debugMsg[] = ' ====================================== ';
            
            $this->debug( PHP_EOL . implode(PHP_EOL, $debugMsg) . PHP_EOL);
        }
    
        $l->layout->template->tryDel('Header');
        //$l->layout->template->trySet('Header',get_class($exception));
        
        if ($this->isJsonRequest()) {
            echo json_encode([
                'success' => false, 'message' => $l->layout->getHtml(),
            ]);
        } else {
            $l->catch_runaway_callbacks = false;
            $l->run();
            $this->run_called = true;
        }
        
        $this->callExit();
    }
```

**Comment by abbadon1334** [comment] 2019-02-19 09:18
![image](https://user-images.githubusercontent.com/5801824/53003533-d2715880-3437-11e9-87dc-348fc531eb53.png)

even in a standard App with atk4/ui@develop this test case works as excepted

**Comment by PhilippGrashoff** [comment] 2019-02-19 09:40
What I meant is if anything but the json the modal expects is sent to it it just keeps on loading forever.

**Comment by abbadon1334** [comment] 2019-02-19 12:01
this is why i started with : But why? and for *but why* i mean why you have to sent extra data to the output in production or in develop stage? in production you have to catch new Exception and new Error that never happen in develop/testing, log it and output an error possible with a specific code, in develop you have catch errors and exception, log it and output to client error/exception.

but i think catching error using set_error_handler like set_exception_handler will be part of the solution, this will stop unexpected output like errors and consequently forever loading of modal : 

```php
<?php

date_default_timezone_set('UTC');

include '../../common.php';

$app = new \atk4\ui\App();

$app->initLayout('Centered');

set_error_handler(function($errno, $errstr, $errfile, $errline) use (&$app) {
    
    $app->catch_runaway_callbacks = false;
    
    $l = new \atk4\ui\App();
    $l->initLayout('Centered');
    
    $error = "<b>Custom error:</b> [$errno] $errstr<br>";
    $error.= " Error on line $errline in $errfile<br>";
    
    $l->layout->template->setHTML('Content', $error);
    
    
    $ajax = false;
    
    // if ($app->isJsonRequest()) <== give error undefined method i dunno why
    
    if (!empty($_SERVER['HTTP_X_REQUESTED_WITH'])
        && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') {
        $ajax = true;
    }
    
    if($ajax && !isset($_GET['__atk_tab'])) {
        echo json_encode(['success'   => false,
                          'message' => $l->layout->getHtml(),
                         ]);
    } else {
        $l->catch_runaway_callbacks = false;
        $l->run();
        $app->run_called = true;
    }
    
    $app->callExit();
    
    return true;
    
},E_ALL);

$modal = $app->add(['Modal']);

$modal->set(function($m) use ($modal) {
    throw new \Exception("TEST!");
});

$button = $app->add(['Button', 'Test modal exception']);
$button->on('click', $modal->show());


$modal2 = $app->add(['Modal']);

$modal2->set(function($m) use ($modal2) {
    trigger_error("error triggered");
});

$button2 = $app->add(['Button', 'Test modal error']);
$button2->on('click', $modal2->show());
```

to catch extra output out of render i think, in construct must be added ob_start and ob_clean in render method, check if is empty and eventually display the content to the user, but as far as i see in atk4 i don't like this workaround, even if is simple and easy/quick to do i think is a bad habit to echo output for debug if you know that can broken something, try logging it because is more easy and have history.

@romaninsh what do you think about adding to atk4/ui/App, catching errors using set_error_handler like set_exception_handler mechanism?

**Comment by abbadon1334** [comment] 2019-02-20 10:31
#655

**Comment by pkly** [comment] 2019-02-27 11:58
I've tried it out, and well, it works. It does catch the exception.
The issue now is that it's being weird about it. The UI glitches out on a modal, unlike what happens when a proper `\atk4\ui\Exception` is generated via some other ajax action. 

Obviously ajax cannot handle additional errors being shown, but I don't agree fully with the way you implemented it. I already have a simple check in my code along the lines of 

```php
if (MyApp::isDebug() && !MyApp::convert($_GET['json'] ?? false, Type::BOOL)) {
    ini_set('display_errors', 1);
    ini_set('display_startup_errors', 1);
    error_reporting(E_ALL);
}
else {
    // json requests can't allow errors
    ini_set('display_errors', 0);
    ini_set('display_startup_errors', 0);
    error_reporting(0);
}
```

so, I don't really like your way of completely overriding them for everything.
You should've checked if the request is an ajax one at the very least, otherwise you're blocking all errors from being shown pretty much outside of atk, which is rather unhealthy, I think.

Regardless, I still believe this file doesn't really need to be modified in the first place. Sure, it's one way to do it, but because of the way the modal ui is being replaced after being loaded, the layout is placed **inside** the actual modal, which is incorrect, as modals have separate layouts...

One of the easiest fixes and best ones I can think of is to modify the atk js code I've posted in the OP.

**Comment by abbadon1334** [comment] 2019-02-28 07:08
> so, I don't really like your way of completely overriding them for everything.
@pkly i think the problem is clearly there, error was controlled only on WARNING level, i extend it to E_ALL and verify every possible situation, with this approach i think in the future those Throwable can be  reduced to a less number of cases, transformed in types, try/catch with certain result and output if needed,log if needed or ignore it if needed.

with the solution #655 i see that every component is well done, at now only for Dropdown and Lookup in case of errors i can't catch anything, because if they receive an error when they except results of function (JS) atkAjaxec, they don't process it and leave the list empty, even if they received a success=false message.

@pkly from my point of view, that simple check you shown above is not a solution, first because json/ajax calls allow errors and secondly because errors happens and must be : 

1. classified
2. catch
3. processed
4. decide to log or ignore
5. decide to output or ignore

@pkly I apologies if I'm getting you involved in a discussion that goes beyond the problem perfectly reported by you, but I think the solution is not to solve that specific problem, but to get to the source of all the problems connected to this issue.


I will fight for this: D because I want this project to grow and I understand that it is frustrating not to know that an error has happened and where it happened, but it is even more so if it happens in javascript.

I think this is one of the possible reason of why a new comer don't continue using atk4 or think that is a good concept and a good product but this issues feels that is still not production ready.

I said this as a personal experience, because i follow the project and try to use it in some little projects but with all this little issues didn't make me comfortable to use it in much larger projects; in the last few months i see some changes and some more activity on atk4 and i decided to be involved and use it in my company future projects and give back components and improvements to the community.

P.S. probably with all this communication i will improve even my english

**Comment by pkly** [comment] 2019-02-28 07:48
@abbadon1334 It's fine, don't worry about it. I'm glad to see there's passionate people working on this project.

I understand why you did it the way you did, but I'd suggest a few changes regardless:

- Disabling error reporting should occur only during AJAX calls, as not to completely block other errors, which could be helpful outside of critical operations
- The js files should be modified to be able to see if an error occured in PHP (They don't seem to check the `response.success` at any point), which could be checked to throw a `new Error` in JS, to force a display of an error, if modified properly this functionality could easily be extended to all the services)

This whole issue appears to be somewhat connected to the `ApiService` class in `/src/services/ApiService.js`, I believe.

The `ModalService` class simply doesn't check for success, no matter what kind of issue arises, I've been running all this on PHP 7.1, and with the errors supressed on AJAX calls.

**Closed** 2019-07-23 10:16 UTC
