### ISSUE TITLE
 <2.0.999 does not fix  Call to undefined method atk4\ui\View::addToWithClUnsafe()

### ISSUE THREAD

**Issue by domainoverflow** [atk4/ui#1306] opened 2020-06-21 21:26 UTC
Now I have half-code in 2.1 :-( 

using  atk4/ui < 2.0.999 did not help. 

Please how can we fix it or is there an actual workaround ? 

Thanks for any help !

**Comment by mvorisek** [comment] 2020-06-22 08:27
It helps - if you do it for all `atk4/*` packages.

Or require `dev-develop`.

**Comment by mvorisek** [comment] 2020-06-22 08:27
duplicate of https://github.com/atk4/ui/issues/1300

**Comment by romaninsh** [comment] 2020-06-22 12:11
@domainoverflow could you please provide more context on the error?

**Comment by domainoverflow** [comment] 2020-06-22 12:12
sure @romaninsh .. writing now..

**Comment by domainoverflow** [comment] 2020-06-22 12:20
I have 8 systems using atk4. I really like your framework.
After 2.1 - I started writing code using 2.1 .. with 2.1 features. 
This led me to a 5 day sprint to fix missing classes everywhere. I mean everywhere.
My issue starts with #1300 .. but I manage to go beyond. 
After 1300 ... when extending the class model it fails ( : void ) 
Then, the Form addToHook is missing. 
It feels I am fixing endlessly. 
I did what I could on composer requireS: .. @dev, <2.0.99, ..
I spent the weekend adapting my new code to 2.0.4 and then honestly I am now 3 days late on a client. 
That's the context. half 2.1 code and half < 2.1 have ruined my life!
thanks for any help

**Comment by mvorisek** [comment] 2020-06-22 12:37
@domainoverflow I understand your concerns. I have already very strongy told @romaninsh what to do to fix it.

And also you.

- If you already use some new features, you can require `dev-develop` version, which is basically 1:1 what you will get with the new upcoming releases.
- In past, there was also one alpha release of this ui repo. If you used it, you may distribute & install the deps using composer.lock file.

There is no other solution.

Next time, I will let you wait for @romaninsh, greeting him :D

**Closed as completed** 2020-06-22 13:06 UTC
Labels: duplicate, invalid

**Comment by romaninsh** [comment] 2020-06-22 13:34
Fix in #1300
