### ISSUE TITLE
2.1 more issues

### ISSUE THREAD

**Issue by domainoverflow** [atk4/ui#1307] opened 2020-06-22 12:06 UTC
The described help in the last two close issues did not help. 
The problem is not limited to that error.
After fixing addToWithCIUnsafe - there are more missing stuff ( Form AddToHook ) and then more. 
I have 2 systems that contains half code of 2.1 and half not. They are totally broken obviously as I did not expect broken backward comp. code.
While I understand this happens, I do not understand the closing of the issue without its resolution. 
There are also a few classes without different inits ( new :voids so children classes fail ... ). 
The solution by @mvorisek did not help.
Thanks for your help.

**Comment by romaninsh** [comment] 2020-06-22 12:08
could you please link issue in question? are you on discord?

**Comment by domainoverflow** [comment] 2020-06-22 12:13
Hi @romaninsh .. 
I see #1300 at least ... I have many times asked for a discord invite :-(

**Comment by mvorisek** [comment] 2020-06-22 12:15
duplicate of https://github.com/atk4/ui/issues/1300

**Closed as completed** 2020-06-22 12:14 UTC
Labels: duplicate, invalid

**Comment by georgehristov** [comment] 2020-06-22 12:59
@domainoverflow here is an invite https://discord.gg/7Myv3Y
