### ISSUE TITLE
Error: Call to undefined method atk4\ui\Form::addTo()

### ISSUE THREAD

**Issue by ghena** [atk4/ui#1113] opened 2020-04-18 09:48 UTC
Using simple example I get this error:
Call to undefined method atk4\ui\Form::addTo()

the class atk4\ui\Form has not a addTo method.
Maybe docs is not updated ?
Please let me know.
Regards.
```
require_once __DIR__ . '/vendor/autoload.php';

use atk4\ui\HelloWorld;
use atk4\ui\Form;

$app = new \atk4\ui\App('My First App');       // 3
$app->initLayout('Centered');

$form = \atk4\ui\Form::addTo($app); // Yeah, that's a form!

$form->addField('email');    // adds field
$form->onSubmit(function ($form) {
    // implement subscribe here

    return $form->success('Subscribed '.$form->model['email'].' to newsletter.');
});

// Decorate anything
$form->buttonSave->set('Subscribe');
$form->buttonSave->icon = 'mail';
```

**Comment by DarkSide666** [comment] 2020-04-19 15:42
You have to grab latest versions from github and then it should work fine.
Which versions are you using? What's in your composer.json file?

**Comment by ghena** [comment] 2020-04-20 06:46
2.0 version.

I just executed composer installation with 7.2.1 php version.

Which is the latest version?

**Comment by PhilippGrashoff** [comment] 2020-04-20 07:31
In most repositories its 2.0.2. You definitely need atk4/core 2.0.2 to use `::addTo()`. Its a replacement for `->add()`. If you are not in yet, feel free to join our discord channel: https://discord.gg/JSeEGm

**Comment by ghena** [comment] 2020-04-20 17:29
It's very strange:

https://github.com/atk4/ui/blob/develop/src/Form.php

has not "addTo" or "add" method:

So I dont understand.

**Comment by DarkSide666** [comment] 2020-04-21 09:39
It's it `/atk4/core/StaticAddToTrait` trait.

**Comment by hdisk13** [comment] 2020-04-27 04:11
I'm also having this same problem with the Quickstart example. 

Error: Call to undefined method atk4\ui\HelloWorld::addTo() (in /var/www/html/agile_ui/index.php:7)

When I ran composer (new tool for me) - this is my output:

[root@robo agile_ui]# composer require atk4/ui
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^2.0 for atk4/ui
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 5 installs, 0 updates, 0 removals
  - Installing psr/log (1.1.3): Loading from cache
  - Installing atk4/core (2.0.2): Loading from cache
  - Installing atk4/dsql (2.0.2): Loading from cache
  - Installing atk4/data (2.0.3): Loading from cache
  - Installing atk4/ui (2.0.4): Loading from cache
atk4/core suggests installing symfony/yaml (~2.1|~3.0|~4.0)
atk4/dsql suggests installing jdorn/sql-formatter (*)
Writing lock file
Generating autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!

I hope someone can see what I'm missing.  This looks like a very nice system to work with.

**Comment by PhilippGrashoff** [comment] 2020-04-27 06:53
Hi @hdisk13,
we are having some new people to ATK having this problem, I want to look into it today and try if I can reproduce the problem. Meanwhile, you can use `->add()`, like `$app->add('HelloWorld');`. ::addTo() is a replacement for it, but somehow there seems to be some trouble.

**Comment by DarkSide666** [comment] 2020-04-27 11:38
```
composer require atk4/ui

Installing psr/log (1.1.3): Loading from cache
Installing atk4/core (2.0.2): Loading from cache
Installing atk4/dsql (2.0.2): Loading from cache
Installing atk4/data (2.0.3): Loading from cache
Installing atk4/ui (2.0.4): Loading from cache
```

Now creating index.php file in web root like this:
```
<?php
require_once __DIR__ . '/vendor/autoload.php';

use atk4\ui\HelloWorld;
use atk4\ui\Form;

$app = new \atk4\ui\App('My First App');       // 3
$app->initLayout('Centered');

$form = \atk4\ui\Form::addTo($app); // Yeah, that's a form!

$form->addField('email');    // adds field
$form->onSubmit(function ($form) {
    // implement subscribe here

    return $form->success('Subscribed '.$form->model['email'].' to newsletter.');
});

// Decorate anything
$form->buttonSave->set('Subscribe');
$form->buttonSave->icon = 'mail';
```

And get error:
```
Error: Call to undefined method atk4\ui\Form::addTo() (in C:\wamp\www\aaa\index.php:10)
```

**Comment by DarkSide666** [comment] 2020-04-27 11:43
Issue happens because in current UI release (2.0.4) there is no `trait StaticAddToTrait` added in View class.

Quick solution:
- use `composer require atk4/develop`
- or use `add()` instead of `addTo` in your code like this:
`$form = $app->add(new \atk4\ui\Form());`

Proper solution - create new UI release 2.0.5.

**Comment by domainoverflow** [comment] 2020-05-09 10:56
I was able to bypass this problem by doing 
composer require atk4/ui:@dev 
AND composer require atk4/ui:@dev 

But this created a new problem in other atk4 related modules. In my case atk4/invoices is now broken. Any ideas ? thanks !

**Comment by DarkSide666** [comment] 2020-05-11 12:05
Well, `atk4/invoices` most likely is not yet compatible with new features of `atk4/ui`.
But other (main) repos should be.

**Comment by domainoverflow** [comment] 2020-05-11 12:41
Well, it's broken.

________________________________

**Comment by DarkSide666** [comment] 2020-05-11 15:04
Commited some compatibility fixed in atk4/invoices. Check out. There is still issue with actions, but other things looks like work again.

**Comment by mvorisek** [comment] 2020-05-18 07:41
Closing, `::addTo()` is fully supported in atk4/ui, in add-on repos it may require some fixes due stricter checks. Any issue need to be reported to the problematic add-on repo.

**Closed as completed by mvorisek** 2020-05-18 07:41 UTC
Labels: bug :beetle:, question, wontfix

**Comment by hdisk13** [comment] 2020-06-01 03:24
I think 'composer' is the problem on this thread.  Maybe what is packaged in the packagist repository is out dated. 

When I follow the tutorial in the documentation - after running 
# composer require atk4/ui

I receive a 'composer.json' that appears to contain version 2.0 (not 2.0.2 that is apparently required for any of the documentation to work)

{
     "require": {
         "atk4/ui": "^2.0"
     }
}

Should I be ignoring the documentation and downloading atk4/ui using git or something else?  

Thank

**Comment by DarkSide666** [comment] 2020-06-01 14:09
i think `^2.0` means any 2.0.x version, but not 2.1.x

**Comment by mvorisek** [comment] 2020-06-01 14:22
https://getcomposer.org/doc/articles/versions.md#caret-version-range- `^2.0` matches all 2.x versions

**Comment by woodholly** [comment] 2024-10-24 18:23
Bug that appears in first tutorial example has not been fixed in 4 years. LOL. This shit will never get popularity.

**Comment by mvorisek** [comment] 2024-10-24 18:36
Thank you for finding the issue. What are steps to reproduce on https://ui.atk4.org/demos/ ?

**Comment by woodholly** [comment] 2024-10-24 18:43
Just follow https://github.com/atk4/ui#how-does-it-work

**Comment by mvorisek** [comment] 2024-10-24 18:47
> Using simple example I get this error: Call to undefined method atk4\ui\Form::addTo()
> 
> the class atk4\ui\Form has not a addTo method. Maybe docs is not updated ? Please let me know. Regards.

The static method `addTo` is defined in `Atk4\Ui\Form` class via https://github.com/atk4/core/blob/5.2.0/src/StaticAddToTrait.php#L37 trait.

**Comment by woodholly** [comment] 2024-10-24 18:51
Yes, don't fix it, put the responsibility on the shoulders of the newbie to open the source code of the project from the first example and find the cause of the error. No pain no gain LOL.

**Comment by mvorisek** [comment] 2024-10-24 18:58
Use the latest version, everything works out of the box already. If you still suffer any issue, the community here is ready to help.

**Comment by woodholly** [comment] 2024-10-24 19:12
Nope, it does not, it has 2 errors in the code.

**Comment by mvorisek** [comment] 2024-10-24 21:04
The demo from README is here https://github.com/atk4/ui/blob/5.2.0/demos/form/form.php#L32-L41 and it is working at https://ui.atk4.org/demos/form/form.php.

**Comment by woodholly** [comment] 2024-10-24 23:44
No one here was talking about the demo.

**Comment by mvorisek** [comment] 2024-10-24 23:49
Last warning. The demo is working, the code equals to the code in README and it equals to your issue on top (with minor changes due updates in v3-v5).

If there is anything we can help you, post here minimal repro code and describe steps to reproduce. And as always, PR with fix/improvement highly welcomed.

**Comment by woodholly** [comment] 2024-10-24 23:55
https://github.com/atk4/ui/issues/1113#issuecomment-2436103298

**Comment by mvorisek** [comment] 2024-10-25 00:04
Please provide a screenshot of the exact error you are getting and confirm you are using the latest `atk4/ui` package installed using composer.
